--1--
CREATE DATABASE LAB1;
--2--
CREATE TABLE USERS(
    ID SERIAL,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50)
)
;
--3--
ALTER TABLE USERS
ADD COLUMN ISADMIN INTEGER;
--4--
ALTER TABLE USERS
ALTER COLUMN ISADMIN  TYPE BOOLEAN USING ISADMIN::BOOLEAN;
--5--
ALTER TABLE USERS
ALTER COLUMN ISADMIN SET DEFAULT 'FALSE'
;
--6--
ALTER TABLE USERS
ADD PRIMARY KEY (ID);
--7--
CREATE TABLE TASKS(
    ID SERIAL,
    NAME VARCHAR(50),
    USER_ID INTEGER
);
--8--
DROP TABLE TASKS;
--9--
DROP DATABASE LAB1;
DROP TABLE USERS;